### ISSUE TITLE
Redirection logic in OslcClient class may be faulty

### ISSUE THREAD

**Issue by Kira-Cesonia** [OSLC/oslc-client#28] opened 2020-07-27 07:57 UTC
This one took me a while to figure out, and in the end, I managed to pinpoint the cause of the problem in `org.eclipse.lyo.client.oslc.OslcClient.getResource(String url, Map<String, String> requestHeaders, String defaultMediaType)`.

But first things first. Here is the error message that got me started:

```
SCHWERWIEGEND: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Target host is null
org.apache.wink.client.ClientRuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Target host is null
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:241)
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:189)
	at org.apache.wink.client.internal.ResourceImpl.invokeNoException(ResourceImpl.java:181)
	at org.apache.wink.client.internal.ResourceImpl.get(ResourceImpl.java:311)
	at org.eclipse.lyo.client.oslc.OslcClient.getResource(OslcClient.java:270)
	at org.eclipse.lyo.client.oslc.OslcOAuthClient.getResource(OslcOAuthClient.java:117)
	at org.eclipse.lyo.client.oslc.OslcClient.getResource(OslcClient.java:204)
	at doors.api.DoorsOauthSampleAdjusted.main(DoorsOauthSampleAdjusted.java:83)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Target host is null
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.handle(ApacheHttpClientConnectionHandler.java:90)
	at org.apache.wink.client.internal.handlers.HandlerContextImpl.doChain(HandlerContextImpl.java:52)
	at org.apache.wink.client.internal.handlers.AcceptHeaderHandler.handle(AcceptHeaderHandler.java:79)
	at org.apache.wink.client.internal.handlers.HandlerContextImpl.doChain(HandlerContextImpl.java:52)
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:228)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Target host is null
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.processRequest(ApacheHttpClientConnectionHandler.java:116)
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.handle(ApacheHttpClientConnectionHandler.java:87)
	... 11 more
Caused by: java.lang.IllegalStateException: Target host is null
	at org.apache.http.util.Asserts.notNull(Asserts.java:52)
	at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:100)
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:761)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:380)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.processRequest(ApacheHttpClientConnectionHandler.java:113)
	... 12 more
```

After tracking this down for a while, I realized that the root cause of the problem is the while-loop in above mentioned function, which goes like this:

```
		do {
			[…]

			response = resource.get();

			if (response.getStatusType().getFamily() == Status.Family.REDIRECTION) {
				url = response.getHeaders().getFirst(HttpHeaders.LOCATION);
				response.consumeContent();
				redirect = true;
			} else {
				redirect = false;
			}
		} while (redirect);
```

Here's what happens when running this, targeting a dwa installation on the local machine:

* On the first iteration, the url is `http://localhost:8080/dwa`
* This begets a 302 redirection response including the header `Location=[/dwa/]`
* Now this line `url = response.getHeaders().getFirst(HttpHeaders.LOCATION);` changes the url from:
** From: `http://localhost:8080/dwa`
** To: `/dwa/`
* Thus, the host is lost, and the next iteration produces the above mentioned "Target host is null” error

So, to sum it up for this particular case:

* When a redirection request is received, the url is changed from `http://localhost:8080/dwa` to `/dwa/`
* It should instead be changed from `http://localhost:8080/dwa` to `http://localhost:8080/dwa/`

For me, this happened on localhost, and appending the trailing "/" right before the `client.getResource` call like follows fixed the problem. 

```
ClientResponse response = client.getResource(url + "/", OSLCConstants.CT_RDF);
```

NOTE: The url in the DoorsOauthSample explicitly needs to have *no* trailing `/`, since calls like `DWA_URL + "/j_acegi_security_check"` rely on it.

However, since this appears to be a problem with the redirection logic, I think this warrants a deeper look.

To reproduce:
* Try following the steps for https://github.com/OSLC/lyo-samples#DoorsOauthSample using a localhost installation of DWA (DWA should be accessible via http://localhost:8080/dwa)
* This error will occur as soon as you try to run the sample file

**Comment by jamsden** [comment] 2020-07-27 12:11
Its likely OslcClient is simply returning the Location header provided by the server. Perhaps the issue is in what the server is producing.

**Comment by berezovskyi** [comment] 2024-02-24 15:50
I will close this issue as this repo is for the JS client and the question was relating to the Java client.

**Closed by berezovskyi** 2024-02-24 15:50 UTC
